apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol2
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle # Retain, Delete
  storageClassName: local-storage
  local:
    path: /mnt/disk/vol2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - redisonokd-node2
